# Generated by Django 4.2.30 on 2026-05-27 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='城市名称')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属省份')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='城市编码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='小区名称')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('build_year', models.IntegerField(blank=True, null=True, verbose_name='建筑年代')),
                ('property_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='物业类型')),
                ('total_houses', models.IntegerField(blank=True, null=True, verbose_name='总户数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '小区',
                'verbose_name_plural': '小区',
                'db_table': 'community',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='区域名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='house.city', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict_date', models.DateField(verbose_name='预测日期')),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预测均价(元/平米)')),
                ('trend', models.CharField(choices=[('上涨', '上涨'), ('下跌', '下跌'), ('平稳', '平稳')], max_length=20, verbose_name='趋势')),
                ('change_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='变化率(%)')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='置信度')),
                ('model_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='模型名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='house.district', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '房价预测',
                'verbose_name_plural': '房价预测',
                'db_table': 'price_prediction',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('交通', '交通'), ('教育', '教育'), ('医疗', '医疗'), ('商业', '商业'), ('生活', '生活')], max_length=50, verbose_name='类型')),
                ('name', models.CharField(max_length=100, verbose_name='设施名称')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='距离(米)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='house.community', verbose_name='所属小区')),
            ],
            options={
                'verbose_name': '周边配套',
                'verbose_name_plural': '周边配套',
                'db_table': 'facility',
            },
        ),
        migrations.AddField(
            model_name='community',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='house.district', verbose_name='所属区域'),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='房源标题')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='总价(万元)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价(元/平米)')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='面积(平米)')),
                ('layout', models.CharField(blank=True, max_length=50, null=True, verbose_name='户型')),
                ('orientation', models.CharField(blank=True, max_length=50, null=True, verbose_name='朝向')),
                ('floor', models.CharField(blank=True, max_length=50, null=True, verbose_name='楼层')),
                ('total_floor', models.IntegerField(blank=True, null=True, verbose_name='总楼层')),
                ('decoration', models.CharField(blank=True, choices=[('精装', '精装'), ('简装', '简装'), ('毛坯', '毛坯'), ('其他', '其他')], max_length=50, null=True, verbose_name='装修情况')),
                ('elevator', models.BooleanField(default=False, verbose_name='是否有电梯')),
                ('listing_date', models.DateField(blank=True, null=True, verbose_name='挂牌日期')),
                ('house_year', models.IntegerField(blank=True, null=True, verbose_name='房屋年限')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='来源链接')),
                ('status', models.IntegerField(choices=[(1, '在售'), (0, '已下架')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='house.community', verbose_name='所属小区')),
            ],
            options={
                'verbose_name': '房源',
                'verbose_name_plural': '房源',
                'db_table': 'house',
                'indexes': [models.Index(fields=['total_price'], name='idx_total_price'), models.Index(fields=['unit_price'], name='idx_unit_price'), models.Index(fields=['area'], name='idx_area'), models.Index(fields=['status'], name='idx_status')],
            },
        ),
    ]
